### ISSUE TITLE
dossier de templates Twig dans les classes PHP

### ISSUE THREAD

**Issue by AymDev** [kimvu264/pamekitchen-sf4#2]
Un dossier [`includes`](https://github.com/kimvu264/pamekitchen-sf4/tree/master/src/includes) se trouve actuellement dans `src`. Il ne doit pas y être, d'autant plus que les templates qui s'y trouvent ne pourront pas être chargés par **Twig** (la configuration de Twig désigne le dossier racine des templates comme étant `templates`).

Il faudrait soit déplacer le dossier, soit le supprimer si son contenu n'est pas utile.

**Comment by KimVu264** [comment]
Nous avons supprimé le dossier includes dans src
